apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  minReadySeconds: 6
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
        version: "1.625.1"
        version: "2.60.3"
    spec:
      containers:
        - name: jenkins
          image: jenkins:1.625.1
          image: jenkins:2.60.3 
          ports:
            - containerPort: 8080
              protocol: TCP