apiVersion: v1
kind: Service
metadata:
  name: ports-sc
  labels:
    app: svc
spec:
  type: ClusterIP
  type: NodePort
  selector:
    app: svc
  ports:
    - name: webport
      port: 35000
      targetPort: 80

      targetPort: 80
      nodePort: 8080